# Generated by Django 5.2.4 on 2025-08-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='text1'),
            preserve_default=False,
        ),
    ]
